### ISSUE TITLE
UserNotice: The assignment in the ... looks like an error.

### ISSUE THREAD

**Issue by Patrik-K2D** [nette/latte#258]
**Version:** v2.10.1

### Bug Description
UserNotice: The assignment in the ... looks like an error.
Assigning to `$primaryString` variable which is used immediately on next line (`$iePrimary === $primaryString`)

### Steps To Reproduce
``` latte
{include #body-row,
	$recordVariable => $record,
	primaryString => ($primaryString = ($record |primaryToString)),
	isInlineEdited => $hasInlineEdit && $iePrimary === $primaryString
}
```

Same issue as in https://github.com/uestla/TwiGrid/issues/40

**Comment by dg** [comment]
fixed

**Comment by tprochazka** [comment]
Weird that it is even worse in 2.10.1, it still crashing and also shows the wrong line number.
I'm using `uestla/twigrid` in version "12.0.0"

![image](https://user-images.githubusercontent.com/172094/107128579-1da00280-68bf-11eb-8a33-57742148c8dd.png)
after upgrad

**Comment by dg** [comment]
Did you try master?

**Comment by tprochazka** [comment]
No. I just checked that 2.10.1 release was after the fix itself.
I tested it now with
`latte/latte (v2.10.x-dev a5946ee): Cloning a5946ee1a7 from cache`
And itis really fixed. Thanks!
